sudo: required
services:
  - docker

before_install:
  - docker build -t audefaucheux/docker-react-tut -f Dockerfile.dev .

script:
  - docker run audefaucheux/docker-react-tut npm run test -- --coverage
