sudo: required
services:
  - docker

before_install:
  - docker build -t audefaucheux/docker-react-tut -f Dockerfile.dev .

script:
  - docker run audefaucheux/docker-react-tut npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-tut-2"
  env: "Dockerreacttut2-env"
  bucket_name: "elasticbeanstalk-us-east-2-550680232637"
  bucket_path: "docker-react-tut-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
